### ISSUE TITLE
Monorepo: Volar imports compiled code instead of source

### ISSUE THREAD

**Issue by everhardt** [johnsoncodehk/volar-starter#7]
I'm using the [monorepo branch](https://github.com/johnsoncodehk/volar-starter/tree/monorepo). I install all packages (`npm i`) and then open VS Code. I ensure `Vue Language Features (Volar)` is enabled for the workspace in take over mode (so I have disabled `TypeScript and JavaScript Language Features`). When I then open App.vue I get the following error on line 8:
```
Cannot find module '@volar-starter/shared' or its corresponding type declarations.
```

That will go away when I compile the TS (`npm run build`) and only then the type information for `sayHello` is available. So it looks like Volar is using the compiled code instead of the source. That is confirmed by the fact that if I let sayHello return a `number` instead of a `string` in the `shared` package, it still has a `string` return in the type information in the `web`-package.

Having used monorepos with plain typescript (so no Vue), I'm not used to having to compile my code before I can use it in another package: TS just imports (and builds!) from source files. Is this something that Volar can also support?

**Comment by johnsoncodehk** [comment]
Fixed by 1bbc90b4c09322143117266f79de956ab3549490.

**Comment by everhardt** [comment]
Sorry for my (very) late reply. I think that's not a monorepo, but just increasing the scope of the "web" TS project to include the sources of "src". To have a monorepo, add to `packages/web/tsconfig.json`:
* `"rootDir": "src"` under `compilerOptions` 
* ```json
  "references": [
    {
      "path": "../shared"
    }
  ]
```

Then you'll have the error `Output file '[...]/volar-starter-monorepo/packages/shared/out/index.d.ts' has not been built from source file '[...]volar-starter-monorepo/packages/shared/src/index.ts'.`

**Comment by everhardt** [comment]
@johnsoncodehk could you please reopen this issue?

**Comment by johnsoncodehk** [comment]
Just add it in https://github.com/johnsoncodehk/volar-starter/commit/4356525bd2e5b87cc691ee1ebd9bb1cb4ff8a136.

**Comment by everhardt** [comment]
You did not set `"rootDir": "src"` under `compilerOptions`, so I think it's still not a monorepo, but a single package?
